### ISSUE TITLE
Sometimes QR code scanner crashes on closing by arrow button

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aepp-base#1162]
Steps to reproduce:
- open send screen
- press Scan button
- press Back Arrow button
- repeat two steps above slowly until "App crashed" message appears (appears after 1-2 times)

**Comment by davidyuk** [comment]
2019-09-05 18:06:04.672 27248-27248/com.aeternity.base E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.aeternity.base, PID: 27248
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.ViewGroup.removeView(android.view.View)' on a null object reference
        at com.bitpay.cordova.qrscanner.QRScanner$28.run(QRScanner.java:780)
        at android.os.Handler.handleCallback(Handler.java:836)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:203)
        at android.app.ActivityThread.main(ActivityThread.java:6361)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
